### ISSUE TITLE
Shouldn't ApplicationinsightsAngularpluginErrorService rethrow the error? 

### ISSUE THREAD

**Issue by Marcel0024** [microsoft/applicationinsights-angularplugin-js#12]
Right now the error get swallowed by the service, which is fine for production.
But using this package in development it's weird not having the errors in the console. Isn't that the desired default behaviour?

**Comment by MSNev** [comment]
For debug scenario's, have you tried using the debug-plugin, I've not tried this with Angular, but is should work to help identify errors

https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-debugplugin-js

**Comment by Marcel0024** [comment]
Another thing, if i want to write another custom error handler to catch all errors it's not possible with https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/src/lib/applicationinsights-angularplugin-error.service.ts#L21 because it swallows the error.

**Comment by MSNev** [comment]
So it sounds to me that what you are really looking for is the ability (a config) to effectively "NOT" have the error handler installed? Which you can do already.

Which would really be the creation of a module without the initializing the error handler... Which I think is called out as part of the Basic Usage 
https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/src/lib/applicationinsights-angularplugin-js.module.ts#L11

And looking at the initialize method, as long as the error service was never created it will be ignored... 
And technically, the error is NOT getting swallowed as it's getting logged (and reported) as requested by this error handler.

Another possible option which I think *might* suite your request would be if we define an "interface" / config the error handler that can be passed in to allow you to override the error handler. So rather than the hard coded class name / instance lookup here https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/src/lib/applicationinsights-angularplugin-js.component.ts#L45
we would just reference the type / config / callback / whatever to set the plugin link to the actual error handler instance...

Where the error handler interface might look something like

export interface IApplicationinsightsErrorService {
  setPlugin(analyticsPlugin: IAppInsights): void;
}

Thoughts?

**Comment by Marcel0024** [comment]
No i don't want to override it exactly. Ok so this is more the scenario i'm talking about:

```@NgModule({
  declarations: [],
  imports: [
    ApplicationinsightsAngularpluginJsModule 
  ],
  providers: [
    {
      provide: ErrorHandler,
      useClass: ApplicationinsightsAngularpluginErrorService,
    },
    {
      provide: ErrorHandler,
      useClass: ErrorHandlerNotifierService,
    },
  ],
  exports: [],
})
export class ErrorHandlerModule{} 
```


1. I always to the error to be logged to application insights,
2. I want to display a notification to the user something went wrong for example. (that's the second ErrorHandler. It could also be logging it to somewhere else)

Right now the error gets posted to application insights and then stops, it doesn't get rethrown, that's what i meant with swallowed. I can not use another custom ErrorHandler.

Most ErrorHandlers just calls `throw error;` after doing their logic; https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/src/lib/applicationinsights-angularplugin-error.service.ts#L23

See this ErrorHandler for example: https://medium.com/@amcdnl/global-error-handling-with-angular2-6b992bdfb59c


Maybe i just missed something.
