### ISSUE TITLE
Missing type declarations in 15.1.1

### ISSUE THREAD

**Issue by Adrii77** [microsoft/applicationinsights-angularplugin-js#153]
Since version 15.1.1, the package dosesn't include TS type declarations anymore.

![Capture d’écran 2024-03-19 à 09 45 47](https://github.com/microsoft/applicationinsights-angularplugin-js/assets/40627664/19ce1538-e70a-4629-9427-a162aed3f8f2)

It works with 15.1.0

**Comment by SteveW94** [comment]
I can confirm this issue...breaked our pipeline today :/

**Comment by MSNev** [comment]
We have now deprecated and marked 15.1.1 as invalid and promoted 15.1.0 back to the latest.

We have an internal infrastructure change in the way the packages are published, and this caused the generated *.tgz to be created from the wrong folder causing the generated package to be invalid.

So we will need to publish a v15.1.2, however, there is another internal infrastructure issue that is blocking our validation / generation pipeline, we are investigating but currently, can't provide a timeline on when this might be fixed so that we can publish a 15.1.2 :-(

**Comment by siyuniu-ms** [comment]
15.1.2 is released, please check in the new version for bug fix

**Comment by SteveW94** [comment]
Thanks a lot for the fast fix!

As far as I can see, everything is compiling again as it should.
Also (at least so far as pipelines are still running^^) automated tests look good again.

I think from my side this can be closed :)

**Comment by Adrii77** [comment]
Thank you very much, it's ok for me too ! :)
