### ISSUE TITLE
Don't swallow exceptions

### ISSUE THREAD

**Issue by WolfspiritM** [microsoft/applicationinsights-angularplugin-js#31]
Hi,

We're currently having the problem that once the error handler is implemented all errors and exceptions are swallowed even if there is no app insights started. Especially in development mode this is a big problem.

As a workaround I've now created a custom error handler but the problem is that without an instrumentation key I can't create the app insights object to pass the error handler via extensionConfig. I've now set up a switch that if appinsights is not created (no instrumentation key in config) then I call:

``` ts
if (config.instrumentationKey) {
  this.appInsights = new ApplicationInsights({
    config: {
      ...
      extensions: [angularPlugin],
      extensionConfig: {
        [angularPlugin.identifier]: {
          router: this.router,
          errorServices: [new CustomErrorHandler()],
        },
      },
     ...
    },
  });
} else {
  ApplicationinsightsAngularpluginErrorService.instance.addErrorHandler(
    new CustomErrorHandler()
  );
}
```

This seem to work but I'm not sure if that is the correct way to do it and I think that the error handler itself should provide such functionality.

**Comment by Marcel0024** [comment]
Hi, 

I raised the same issue a while ago: https://github.com/microsoft/applicationinsights-angularplugin-js/issues/12
They added this: https://github.com/microsoft/applicationinsights-angularplugin-js/pull/13

Which means your custom error handler have to implement the IErrorService of this plugin...

**Comment by WolfspiritM** [comment]
@Marcel0024 Thanks, but that doesn't work if the plugin is not even started.

In our case for example the instrumentationKey for local development is not set and therefor "new ApplicationInsights" is not called at all and no extensionConfig can be passed. And without an instrumentationkey there is no way as far as I can see to call "new ApplicationInsights".

**Comment by MSNev** [comment]
Hi @WolfspiritM, sorry for the delay.

Question: Why do you not want to initialize the SDK during development?
I would think a slightly better approach would be to always "initialize" the SDK but pass in an "invalid" instrumentation Key (such as "MyDevelopmentKey" or something -- doesn't really matter) and then as part of the "config" you can do 2 things
1. Set the `disableInstrumentationKeyValidation` to true (so the SDK still "starts"
2. Set the [endpointUrl](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts#L70) to something local "http://localhost/blah" so that no telemetry actually leaves your environment

This way your local dev environment is a closer match with a deployed production one...
