### ISSUE TITLE
microsoft-applicationinsights-angularplugin-js.mjs error EcmaScript. 

### ISSUE THREAD

**Issue by ensgenc** [microsoft/applicationinsights-angularplugin-js#41]
Hi,

Angular: 11.2.4
version 2.6.2 also builds without errors. But after the latest version I am getting the following error.

Before : "@microsoft/applicationinsights-angularplugin-js": "^2.6.2",
After : "@microsoft/applicationinsights-angularplugin-js": "2.6.2",

after doing that it was fixed.

ES3 support was removed after version 2.6.3, but I was not getting any errors in the build. I'm getting an error in 2.8.

**NOT: I saw that angular 13 support came in version 2.8. Does the problem come from that?**

Error: ./node_modules/@microsoft/applicationinsights-angularplugin-js/fesm2015/microsoft-applicationinsights-angularplugin-js.mjs 79:30-49
Can't import the named export 'BaseTelemetryPlugin' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/vsts/work/1/s/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/vsts/work/1/s/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (/home/vsts/work/1/s/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:55:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 @ ./apps/b2b-app/src/app/app.module.ts
 @ ./apps/b2b-app/src/main.ts
 @ multi ./apps/b2b-app/src/main.ts

**Comment by roopeshreddy** [comment]
We too had the similar issue and we're on Angular v11.

**Comment by MSNev** [comment]
Creating a specific Angular 11 release to support Application Insights v2.7.4 as BaseTelemetryPlugin was added in later releases to support automatic upgrades.

**Comment by MSNev** [comment]
Ok, I've just released an Angular 11 v2.7.1 which is targeting Application Insights v2.7.4, if you upgrade both to these version this will (I believe) resolve the TypeScript warnings you are seeing.

For the `ES3 support was removed after version 2.6.3` This was specifically driven (I believe) by Angular 11 and you should still be able to support an ES3 environment by installing ES3 (IE8) polyfills, the trick is to load them first to ensure that libraries that use non-ES3 compliant functions (directly) still function.

Currently the 2.x.x ApplicationInsights versions support ES3 by using internal ES3 helpers (rather than global polyfills) so that we don't interfere with apps that detect ES3 by the presence of unsupported functions. From version 3.x (of Application Insights -- later this year) will be removing the internal usage of these helpers and it will require either an ES5+ runtime environment or you install polyfills before starting the SDK.

Generally, we provide backward compatibility in Application Insights (AI core will load and run older plugins), but we don't support or guarantee forward compatibility (which I think is your error) where a component built with a newer version of AI works with an older SDK as the newer components want to features that don't exist in older versions. This is why we generally set the "base" required version in the package.json

**Comment by MSNev** [comment]
Closing for now as I believe upgrading to the latest version for Angular 11 (2.7.1) with Application Insights 2.7.4 should resolve your issue.

And using ES3 polyills if necessary -- or alternatively keeping with the previous versions.

I've also created a discussion issue to see how we might better support versioning. https://github.com/microsoft/applicationinsights-angularplugin-js/issues/57

**Comment by MSNev** [comment]
@ensgenc, I believe that I have finally found and fixed the IE8 (ES3) issue that broke 2.6.3. I've just published v2.7.2 which is using Application Insights v2.7.5 which should address the issue -- If you get a chance can you please validate that this addresses your original issue

**Comment by MSNev** [comment]
v2.7.2 is still for Angular11 and I'm in the process of creating a 2.9.1 for Angular 13 to provide the same set of fixes using Application Insights 2.8.2
