### ISSUE TITLE
InstrumentationKey should not be needed if connectionString is already present

### ISSUE THREAD

**Issue by urielzen** [microsoft/applicationinsights-angularplugin-js#61]
I am already providing the connectionString in the config, which I thought it was enough for it to work

![image](https://user-images.githubusercontent.com/7947179/168966221-1a5f6dfd-e636-4b6c-928f-eae2050d92c3.png)

But the app throws an error expecting the `instrumentationKey` property also to be added

![image](https://user-images.githubusercontent.com/7947179/168966710-99dbe26f-c116-4021-989b-95451cdf99e6.png)

Im using the following versions

```
    "@microsoft/applicationinsights-angularplugin-js": "^2.9.1",
    "@microsoft/applicationinsights-web": "~2.8.2",
```

**Comment by MSNev** [comment]
Event if you provide a `connectionString` configuration, it MUST include an `instrumentationKey` (as part of the connection string).

I believe that is what is triggering this error, for development purposes include either a dummy "looking" instrumentationKey (in the connection string) or just add something like "testInstrumentationKey" and disable the instrumentation key validation by adding `disableInstrumentationKeyvalidation: true` to you configuration.

However, a better option would be to have a 2nd Azure Monitor account which is used only for testing and use that connection string / key so that you can validate that your system is configured correctly. And for development purposes (if your targetting a browser environment) you can install the [Chrome Debug Extension](https://github.com/microsoft/ApplicationInsights-JS/tree/master/tools/chrome-debug-extension) so that you can more easily see the data being sent (even if you are using a dummy instrumentation key)

**Comment by urielzen** [comment]
I was already including the instrumentation key as part of the connection string, and I was getting the error anyway.

To get around the console error, now I am including the actual instrumentation key also in the `instrumentationKey` property.

But I didn't like that approach I am following because now I had to maintain the correct instrumentation key in two settings/properties. Or so I thought, but from your comment, am I assuming correctly that I can have a dummy key in the `instrumentationKey` property as long as the correct key is in the connection string?

But I think I like better the idea of setting `disableInstrumentationKeyValidation` to true. So I can just maintain the correct key in the connection string only and get rid of the dummy one at `instrumentationKey` property.

Did I understand that correctly?

Thanks for the Chrome Extension, I will check that out.

**Comment by MSNev** [comment]
Yes, but you should not need the `instrumentationKey` in the config at all, here is where the connection string is parsed and it will effectively "replace" any `istrumentationKey` https://github.com/microsoft/ApplicationInsights-JS/blob/master/AISKU/src/Initialization.ts#L185-L190

However, what I did notice as part of finding this code is that the `instrumentationkey` in the connection string "MUST" be all lowercase (not capital "K" for the Key)

The "validation" of the instrumentation key doesn't happen until the "Sender" is initialized which (should be <- not tested as part of this response) after the above code as the above IS the code that starts the entire initialization of the extensions.

**Comment by urielzen** [comment]
Oh I see, problem was that I copied the connection string as shown in the Azure Portal. With the key names in pascal case.
![image](https://user-images.githubusercontent.com/7947179/182997552-b72f790b-bc3f-4f14-a11e-1b00b830f102.png)
The code you referenced also has the `ingestionendpoint` all in lower case, different from the Azure Portal.

**Comment by urielzen** [comment]
Ok I just noticed that the `parseConnectionString` function has a toLowerCase() applied to they key name, so it should not matter if my connections string had uppercase in it. I think I am making a mistake somewhere else in my code.  I think the plug in is working as expected. Thanks for your help.

https://github.com/microsoft/ApplicationInsights-JS/blob/b14bb3360d7cf4de64e010296c986dbcfc2b887c/shared/AppInsightsCommon/src/ConnectionStringParser.ts#L22
